version: '3'
services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    ports:
      - "8080:8080"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
    networks:
      - spark-net

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - spark-net

  spark-worker-aws:
    image: bitnami/spark:latest
    container_name: spark-worker-aws
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://172.22.131.30:7077  # Aquí va la IP pública de la instancia EC2
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge
